### PR TITLE
Patch clickable

### PR DESCRIPTION
**Pull request by johnd0e**
I suppose all these also need to be fixed?

---
This change is [Reviewable](https://reviewable.io/reviews/mcben/ingress-intel-total-conversion/2)

### CODE REVIEW

**Comment by McBen** [comment]
I try to keep the externals unmodified if possible.
Since Leaflet 1+ has a better mouse-event handling the 'clickable:false' -> 'interactive:false' change is in most cases just a visual issue.

**Comment by johnd0e** [comment]
Would it be better if externals be dynamically patching, during build process?

It's not rare case when it's hard to correctly click/touch portal or some other element.
The reason for me often is not clear, so I prefer over-fixing.

**Comment by johnd0e** [comment]
P.S.
There is also separate commit with changes to iits own plugins.

**Comment by johnd0e** [comment]
layer-count plugin still doesn't work in updated leaflet..
(If you are interested in such reports then please open issues section of the repository)

**Comment by johnd0e** [comment]
> I try to keep the externals unmodified if possible.

Could you explain please why not fix the plugins?
 max-links.user.js
 zaprange.user.js

**Comment by McBen** [comment]
no, reason. just a "I'll do it later"

**Pull request closed without merging**
